defaults:
  snmp_version: "v2c"
  timeout_s: 2.5
  retries: 1
  target_budget_s: 10
  oids:
    - "sysUpTime.0"
    - "sysName.0"

targets:
  - name: "Linn"
    ip: "172.16.0.251"
    community: "public"
    oids:
      - "ifOperStatus.1"

  - name: "Katarina"
    ip: "172.16.0.250"
    community: "public"

  - name: "Stina"
    ip: "172.16.0.235"
    community: "public"

  - name: "Lisa"
    ip: "172.16.0.220"
    community: "public"